apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: one-zone-vct-resources-no-storage
spec:
  zones:
    - servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: disk1
        spec:
          resources:
            request:
              cpu: 1.0

