apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: one-zone-no-creds-secret
spec:
  zones:
    - servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: disk1
        spec:
          resources:
            requests:
              storage: 2Gi
          accessModes:
            - ReadWriteOnce
