apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: minio
spec:
  zones:
    - volumesPerServer: 4
      ## Number of MinIO servers/pods in zone 0.
      servers: 4
    - volumesPerServer: 4
      ## Number of MinIO servers/pods in zone 1.
      servers: 4
